version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - CORS_ORIGINS=http://localhost:8080,http://192.168.1.81:8080
    networks:
      - treasure-hunt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/workspace
      - /workspace/frontend/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - treasure-hunt-network

networks:
  treasure-hunt-network:
    driver: bridge 