version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8086:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - CORS_ORIGINS=http://localhost:8085,https://treasure.ghuboss.com
    networks:
      - treasure-hunt-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/workspace
      - /workspace/frontend/node_modules
    environment:
      - NODE_ENV=development
      #- REACT_APP_API_URL=http://localhost:8086
      #- REACT_APP_DEBUG=true
      - PORT=80
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - treasure-hunt-network
    restart: always

networks:
  treasure-hunt-network:
    driver: bridge