version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - CORS_ORIGINS=http://localhost:8080,http://192.168.1.81:8080
    networks:
      - treasure-hunt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/workspace
      - /workspace/frontend/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_DEBUG=false
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - treasure-hunt-network

networks:
  treasure-hunt-network:
    driver: bridge 